# Generated by Django 4.2.25 on 2026-03-25 11:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TBS ENTERPRISES', max_length=255)),
                ('address', models.TextField(default='No.22, MMS Complex, Pudupattinam, Kalpakkam - 603102')),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('state_code', models.CharField(default='33', max_length=5)),
                ('gstin', models.CharField(default='33AHOPY8219N1ZE', max_length=20)),
                ('mobile', models.CharField(default='9655246269', max_length=15)),
                ('email', models.EmailField(default='tbsenterprises2019@gmail.com', max_length=254)),
                ('bank_holder_name', models.CharField(default='M/S TBS ENTERPRISES', max_length=255)),
                ('bank_name', models.CharField(default='UNION BANK', max_length=100)),
                ('bank_account_no', models.CharField(default='510101006884868', max_length=50)),
                ('bank_ifsc', models.CharField(default='UBIN0935051', max_length=20)),
                ('bank_branch', models.CharField(default='Kadalur Village', max_length=100)),
                ('footer_note', models.TextField(default='* This is a computer generated invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('delivery_note', models.CharField(blank=True, max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('buyer_order_no', models.CharField(blank=True, max_length=100)),
                ('buyer_order_date', models.DateField(blank=True, null=True)),
                ('dispatch_doc_no', models.CharField(blank=True, max_length=50)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('ONLINE', 'Online Transfer'), ('CONTRACT', 'As Per Contract Terms & Conditions')], default='CONTRACT', max_length=50)),
                ('destination', models.CharField(default='Kalpakkam, Tamil Nadu-603102', max_length=255)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField()),
                ('buyer_gstin', models.CharField(blank=True, max_length=20)),
                ('buyer_state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('buyer_state_code', models.CharField(default='33', max_length=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rounded_off', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
                ('hsn_sac_code', models.CharField(db_index=True, max_length=20)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('hsn_sac_code', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productmaster')),
            ],
        ),
    ]
