# Generated by Django 4.2.25 on 2026-03-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
      
    ]
