# Generated by Django 4.2.25 on 2026-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productmaster_hsn_sac_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='description',
            field=models.TextField(),
        ),
    ]
