# Generated by Django 4.2.25 on 2026-03-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productmaster_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='hsn_sac_code',
            field=models.TextField(),
        ),
    ]
