# Generated by Django 4.2.25 on 2026-03-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invoiceitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deleivery_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleivery_gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleivery_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleivery_state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleivery_state_code',
            field=models.CharField(default='33', max_length=5),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='bank_holder_name',
            field=models.CharField(default='M/S JRC WORKMATE TRADING', max_length=255),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(default='JRC WORKMATE TRADING', max_length=255),
        ),
    ]
