# Generated by Django 4.2.25 on 2026-03-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invoice_deleivery_address_invoice_deleivery_gstin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='deleivery_address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='deleivery_gstin',
            new_name='delivery_gstin',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='deleivery_name',
            new_name='delivery_name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='deleivery_state',
            new_name='delivery_state',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='deleivery_state_code',
            new_name='delivery_state_code',
        ),
    ]
