# Generated by Django 4.2.25 on 2026-03-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_deleivery_address_invoice_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
