# Generated by Django 4.2.25 on 2026-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_invoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dispatch_through',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_of_delivery',
            field=models.CharField(default='', max_length=255),
        ),
    ]
