# Generated by Django 4.2.25 on 2026-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invoice_dispatch_through_invoice_terms_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='seal_signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
