# Generated by Django 4.2.25 on 2026-04-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_companysettings_seal_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='igst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='igst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
