# Generated by Django 4.2.25 on 2026-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_invoiceitem_igst_amount_invoiceitem_igst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mode_of_transport',
            field=models.CharField(default='', max_length=150),
        ),
    ]
