# Generated by Django 4.2.25 on 2026-04-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_invoice_mode_of_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
