# Generated by Django 4.2.25 on 2026-04-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_invoice_delivery_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(default='', max_length=50),
        ),
    ]
