# Generated by Django 4.2.25 on 2026-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_invoice_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='terms_of_delivery',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
