# Generated by Django 4.2.25 on 2026-04-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_invoice_terms_of_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='igst_percentage',
        ),
        migrations.AddField(
            model_name='invoice',
            name='use_igst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='part_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='use_igst',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
