# Generated by Django 4.2.25 on 2026-04-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_invoiceitem_cgst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sprife_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
