# Generated by Django 4.2.25 on 2026-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_invoice_final_total_invoice_sprife_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sprife_label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
